# @format

global:
  scrape_interval: 5s # Check for new data every 5 seconds

scrape_configs:
  - job_name: "go-backend"
    static_configs:
      # In Docker Compose, "app" will resolve to your Go containers
      - targets: ["app:8080"]
